### ISSUE TITLE
Error: Invalid plugin github repository 

### ISSUE THREAD

**Issue by dnhook123** [davideicardi/live-plugin-manager#70]
Hi.

Im trying to use the live-plugin-manager library to load my custom-made module(Typescript) from a public github repo during runtime. But it errors with the following: 
```
/Users/david/WebstormProjects/send_help/node_modules/live-plugin-manager/dist/src/GithubRegistryClient.js:67
                throw new Error("Invalid plugin github repository " + repository);
                      ^

Error: Invalid plugin github repository dnhook123/modules#25c265c
    at GithubRegistryClient.<anonymous> (/Users/david/WebstormProjects/send_help/node_modules/live-plugin-manager/dist/src/GithubRegistryClient.js:67:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/david/WebstormProjects/send_help/node_modules/live-plugin-manager/dist/src/GithubRegistryClient.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

the index.js code `import {PluginManager} from 'live-plugin-manager';
const manager = new PluginManager();

const test = await manager.queryPackageFromGithub('dnhook123/modules#25c265c');
`

I've already found out that the github repo's like express.js works but mine do not.

My github example: [](https://github.com/dnhook123/send_help)

**Comment by dnhook123** [comment]
Because i have a custom made ts module that i want to import during runtime, do you perhaps know what are the requirements for being able to import such module (from github)?

**Comment by dnhook123** [comment]
Another random question, can this library run .TS files (index.ts) aswell?
