### ISSUE TITLE
Axios dependency failed to install

### ISSUE THREAD

**Issue by KrzysztofTyply** [davideicardi/live-plugin-manager#95]
Hi, great work.

I have the following issue, one of my plugins uses Axios as a dependency
Then while requiring my plugin  I get the following error
```
...
				import axios from './lib/axios.js';
				^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:99:7)
    at PluginVm.vmRunScriptInSandbox (node_modules/live-plugin-manager/dist/src/PluginVm.js:143:24)
    at PluginVm.load (node_modules/live-plugin-manager/dist/src/PluginVm.js:66:22)
    at PluginVm.sandboxRequire (node_modules/live-plugin-manager/dist/src/PluginVm.js:271:25)
```

**Comment by davideicardi** [comment]
See https://github.com/davideicardi/live-plugin-manager/issues/59
